# Generated by Django 2.0.1 on 2018-03-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
