# Generated by Django 2.0.1 on 2018-03-04 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departue_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 18, 7, 48, 238896, tzinfo=utc)),
        ),
    ]
