# Generated by Django 2.0.1 on 2018-03-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='number_seats',
            field=models.IntegerField(default='unspecified'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_booked',
            field=models.IntegerField(default='unspecified'),
        ),
    ]
