# Generated by Django 2.0.1 on 2018-03-04 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0002_auto_20180304_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departue_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
