# Generated by Django 2.0.1 on 2018-03-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0002_auto_20180302_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ONHOLD', 'ONHOLD'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('TRAVELLED', 'TRAVELLED')], default='ONHOLD', max_length=10),
        ),
    ]
