# Generated by Django 2.0.1 on 2018-03-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0003_auto_20180308_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
