# Generated by Django 2.0.1 on 2018-03-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0003_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='aircraft_type',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='ticket_price',
        ),
    ]
