# Generated by Django 2.0.1 on 2018-03-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0004_auto_20180303_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_datetime',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departue_datetime',
        ),
    ]
