# Generated by Django 2.0.1 on 2018-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0004_auto_20180311_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='reference_number',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
