# Generated by Django 2.0.1 on 2018-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0005_auto_20180311_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stamp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
