# Generated by Django 2.0.1 on 2018-03-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0005_auto_20180303_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='number_seats',
            new_name='aircraft_number_seats',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='registration_number',
            new_name='aircraft_registration_number',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='country',
            new_name='airport_country',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='name',
            new_name='airport_name',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='time_zone',
            new_name='airport_time_zone',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='flight',
            new_name='booking_flight',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='number',
            new_name='booking_number',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='number_booked',
            new_name='booking_seats_number',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='number',
            new_name='flight_number',
        ),
    ]
