# Generated by Django 2.0.1 on 2018-03-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0006_invoice_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ammount',
            new_name='amount',
        ),
    ]
